FROM python:3.7-alpine3.8

WORKDIR /workdir

COPY requirements.txt .
RUN apk add git && pip install --prefix=/workdir -r requirements.txt

COPY netjson_python-3.7.pth /workdir/lib/

COPY netjson_path /workdir/bin/
RUN chmod +x /workdir/bin/netjson_path

RUN tar cfz /asset.tar.gz .
